CREATE DATABASE SERS_DB
DROP DATABASE SERS_DB

USE master;
GO
ALTER DATABASE SERS_DB1 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE SERS_DB;
GO

CREATE TABLE Societies(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name VARCHAR(50) UNIQUE NOT NULL,
	Description VARCHAR(2000)
)

SELECT * FROM Societies
DELETE Societies -- DELETE DATA
DROP TABLE Societies -- DELETE TABLE

CREATE TABLE Members(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name VARCHAR(50) NOT NULL,
	Username VARCHAR(50) UNIQUE NOT NULL,
	Role VARCHAR(50) NOT NULL,
	Hashpassword VARCHAR(100) NOT NULL,
	ProfileImage VARCHAR(100),
	SocietyId UNIQUEIDENTIFIER,
	FOREIGN KEY (SocietyId) REFERENCES Societies(Id)
)

SELECT * FROM Members
DELETE Members-- DELETE DATA
DROP TABLE Members -- DELETE TABLE

CREATE TABLE EventRequisitions(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Subject VARCHAR(255) NOT NULL,
	Body VARCHAR(2000) NOT NULL,
	Status VARCHAR NOT NULL,
	ReviewMessage VARCHAR(255),
	RequestedDate DATE NOT NULL,
	AllocatedDate DATE,
	RequestAmount Decimal NOT NULL,
	AllocatedAmount Decimal,
	BiitContribution Decimal,
)

SELECT * FROM EventRequisitions
DELETE EventRequisitions -- DELETE DATA
DROP TABLE EventRequisitions -- DELETE TABLE
ALTER TABLE EventRequisitions 
DROP COLUMN RequestedDate
ALTER TABLE EventRequisitions 
ADD RequestedDate DATE;


CREATE TABLE Events(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name VARCHAR(50) NOT NULL,
	StartTime TIME NOT NULL,
	EndTime TIME NOT NULL,
	EventDate Date NOT NULL,
	Status VARCHAR(10) NOT NULL,
	ReviewMessage VARCHAR(100),
	SocietyId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (SocietyId) REFERENCES Societies(Id),
	RequisitionId UNIQUEIDENTIFIER,
	FOREIGN KEY (RequisitionId) REFERENCES EventRequisitions(Id),
)

ALTER TABLE Events
ADD VirtualSocietyId UNIQUEIDENTIFIER NULL;

ALTER TABLE Events
ADD CONSTRAINT FK_Events_VirtualSocieties
FOREIGN KEY (VirtualSocietyId)
REFERENCES VirtualSocieties(Id);

SELECT * FROM Events
DELETE Events -- DELETE DATA
DROP TABLE Events -- DELETE TABLE


CREATE TABLE EventRequirements(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Type VARCHAR(20) NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Price DECIMAL,
	Quantity INT NOT NULL,
	EventId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (EventId) REFERENCES Events(Id)
)

SELECT * FROM EventRequirements
DELETE EventRequirements -- DELETE DATA
DROP TABLE EventRequirements -- DELETE TABLE

SELECT * FROM EventRequisitions where Id = (SELECT RequisitionId FROM Events where SocietyId = 'CFA9EA19-11D3-4834-07E7-08DEB7EC3EC8' )
SELECT * FROM EventRequisitions WHERE Id IN (SELECT RequisitionId FROM Events WHERE SocietyId = 'CFA9EA19-11D3-4834-07E7-08DEB7EC3EC8')



CREATE TABLE EventAudits(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FundProvided DECIMAL NOT NULL,
	SpendAmount DECIMAL NOT NULL,
	RevenueGenerated DECIMAL NOT NULL,
	RemainingAmount DECIMAL NOT NULL,
	Status VARCHAR(10) NOT NULL,

	EventId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (EventId) REFERENCES Events(Id)
)

SELECT * FROM EventAudits
DELETE EventAudits -- DELETE DATA
DROP TABLE EventAudits -- DELETE TABLE

CREATE TABLE AuditSpends(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Vender VARCHAR(50) NOT NULL,
	Description VARCHAR (255),
	Amount DECIMAL NOT NULL,
	ReceiptPicture VARCHAR(MAX),
	EventAuditId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (EventAuditId) REFERENCES EventAudits(Id)
)

SELECT * FROM AuditSpends
DELETE AuditSpends -- DELETE DATA
DROP TABLE AuditSpends -- DELETE TABLE




CREATE TABLE YearlyBudgets (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Session VARCHAR(50) NOT NULL,
    RequestedAmount DECIMAL NOT NULL,
    AllotedAmount DECIMAL NULL,

    RequestedDate DATE NOT NULL,
    AllotedDate	 DATE NULL,

    Credits DECIMAL NULL,

	SocietyId UNIQUEIDENTIFIER,
	FOREIGN KEY (SocietyId) REFERENCES Societies(Id)

);

SELECT * FROM YearlyBudget
DELETE YearlyBudget -- DELETE DATA
DROP TABLE YearlyBudget -- DELETE TABLE


CREATE TABLE YearlyEvents (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name VARCHAR(150) NOT NULL,
    EstimateAmount DECIMAL NOT NULL,
    EstimateMonth VARCHAR(30) NOT NULL,
    YearlyBudgetId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (YearlyBudgetId) REFERENCES YearlyBudgets(Id)
);

SELECT * FROM YearlyEvents
DELETE YearlyEvents -- DELETE DATA
DROP TABLE YearlyEvents -- DELETE TABLE


CREATE TABLE YearlyEventRequirements (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name VARCHAR(20) NOT NULL,
    EstimatePrice DECIMAL NOT NULL,

    YearlyEventId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (YearlyEventId) REFERENCES YearlyEvents(Id)

);

-- <<<<<<< HEAD
-- SELECT * FROM YearlyEventRequirements
-- DELETE YearlyEventRequirements -- DELETE DATA
-- DROP TABLE YearlyEventRequirements -- DELETE TABLE
-- =======

SELECT * FROM YearlyEventRequirement
DELETE YearlyEventRequirement -- DELETE DATA
DROP TABLE YearlyEventRequirement -- DELETE TABLE


CREATE TABLE YearlyBudgetScrutinies(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name VARCHAR(50) NOT NULL,
	Comment VARCHAR(1000) NOT NULL,
	Date DATE NOT NULL,
	MemberId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (MemberId) REFERENCES Members(Id),
	YearlyBudgetId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (YearlyBudgetId) REFERENCES YearlyBudgets(Id)
)

SELECT * FROM YearlyBudgetScrutinies
DELETE YearlyBudgetScrutinies -- DELETE DATA
DROP TABLE YearlyBudgetScrutinies -- DELETE TABLE



CREATE TABLE VirtualSocieties(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name VARCHAR(50) NOT NULL,
	Description VARCHAR(2000),
	TotalContribution DECIMAL,
	RegistrationEndDate DATE NOT NULL,
	MemberId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (MemberId) REFERENCES Members(Id)
)

ALTER TABLE VirtualSocieties
ADD RegistrationEndDate DATE

SELECT * FROM VirtualSocieties
DELETE VirtualSocieties -- DELETE DATA
DROP TABLE VirtualSocieties -- DELETE TABLE

CREATE TABLE VirtualSocietyContributions(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Contribution DECIMAL NOT NULL,
	VirtualSocietyId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (VirtualSocietyId) REFERENCES VirtualSocieties(Id),
	SocietyId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (SocietyId) REFERENCES Societies(Id)
)

SELECT * FROM VirtualSocietyContributions
DELETE VirtualSocietyContributions -- DELETE DATA
DROP TABLE VirtualSocietyContributions -- DELETE TABLE

